from __future__ import annotations

from lldb_mix.arch.abi import RISCV_ABI, RISCV_X_ABI
from lldb_mix.arch.base import ArchSpec

RISCV_ALIAS_TO_X = {
    "zero": "x0",
    "ra": "x1",
    "sp": "x2",
    "gp": "x3",
    "tp": "x4",
    "t0": "x5",
    "t1": "x6",
    "t2": "x7",
    "s0": "x8",
    "fp": "x8",
    "s1": "x9",
    "a0": "x10",
    "a1": "x11",
    "a2": "x12",
    "a3": "x13",
    "a4": "x14",
    "a5": "x15",
    "a6": "x16",
    "a7": "x17",
    "s2": "x18",
    "s3": "x19",
    "s4": "x20",
    "s5": "x21",
    "s6": "x22",
    "s7": "x23",
    "s8": "x24",
    "s9": "x25",
    "s10": "x26",
    "s11": "x27",
    "t3": "x28",
    "t4": "x29",
    "t5": "x30",
    "t6": "x31",
}

RISCV_X_TO_ALIAS = {
    "x0": "zero",
    "x1": "ra",
    "x2": "sp",
    "x3": "gp",
    "x4": "tp",
    "x5": "t0",
    "x6": "t1",
    "x7": "t2",
    "x8": "s0",
    "x9": "s1",
    "x10": "a0",
    "x11": "a1",
    "x12": "a2",
    "x13": "a3",
    "x14": "a4",
    "x15": "a5",
    "x16": "a6",
    "x17": "a7",
    "x18": "s2",
    "x19": "s3",
    "x20": "s4",
    "x21": "s5",
    "x22": "s6",
    "x23": "s7",
    "x24": "s8",
    "x25": "s9",
    "x26": "s10",
    "x27": "s11",
    "x28": "t3",
    "x29": "t4",
    "x30": "t5",
    "x31": "t6",
}

_RISCV_X_GPRS = tuple(f"x{i}" for i in range(32))
_RISCV_ABI_GPRS = (
    "zero",
    "ra",
    "sp",
    "gp",
    "tp",
    "t0",
    "t1",
    "t2",
    "s0",
    "fp",
    "s1",
    "a0",
    "a1",
    "a2",
    "a3",
    "a4",
    "a5",
    "a6",
    "a7",
    "s2",
    "s3",
    "s4",
    "s5",
    "s6",
    "s7",
    "s8",
    "s9",
    "s10",
    "s11",
    "t3",
    "t4",
    "t5",
    "t6",
)

_CALL_MNEMONICS = (
    "jal",
    "jalr",
    "call",
    "c.jal",
    "c.jalr",
)


class RiscvArch(ArchSpec):
    def is_unconditional_branch(self, mnemonic: str) -> bool:
        mnem = mnemonic.lower()
        return mnem in {"b", "j", "jr", "c.j", "c.jr"}


RISCV32_X_ARCH = RiscvArch(
    name="riscv32",
    ptr_size=4,
    gpr_names=_RISCV_X_GPRS + ("pc",),
    pc_reg="pc",
    sp_reg="x2",
    flags_reg=None,
    special_regs=(),
    max_inst_bytes=4,
    return_reg="x10",
    nop_bytes=b"\x13\x00\x00\x00",
    break_bytes=b"\x73\x00\x10\x00",
    abi=RISCV_X_ABI,
    call_mnemonics=_CALL_MNEMONICS,
)

RISCV64_X_ARCH = RiscvArch(
    name="riscv64",
    ptr_size=8,
    gpr_names=_RISCV_X_GPRS + ("pc",),
    pc_reg="pc",
    sp_reg="x2",
    flags_reg=None,
    special_regs=(),
    max_inst_bytes=4,
    return_reg="x10",
    nop_bytes=b"\x13\x00\x00\x00",
    break_bytes=b"\x73\x00\x10\x00",
    abi=RISCV_X_ABI,
    call_mnemonics=_CALL_MNEMONICS,
)

RISCV32_ABI_ARCH = RiscvArch(
    name="riscv32",
    ptr_size=4,
    gpr_names=_RISCV_ABI_GPRS + ("pc",),
    pc_reg="pc",
    sp_reg="sp",
    flags_reg=None,
    special_regs=(),
    max_inst_bytes=4,
    return_reg="a0",
    nop_bytes=b"\x13\x00\x00\x00",
    break_bytes=b"\x73\x00\x10\x00",
    abi=RISCV_ABI,
    call_mnemonics=_CALL_MNEMONICS,
)

RISCV64_ABI_ARCH = RiscvArch(
    name="riscv64",
    ptr_size=8,
    gpr_names=_RISCV_ABI_GPRS + ("pc",),
    pc_reg="pc",
    sp_reg="sp",
    flags_reg=None,
    special_regs=(),
    max_inst_bytes=4,
    return_reg="a0",
    nop_bytes=b"\x13\x00\x00\x00",
    break_bytes=b"\x73\x00\x10\x00",
    abi=RISCV_ABI,
    call_mnemonics=_CALL_MNEMONICS,
)
